### ISSUE TITLE
Feature: Track Superminority

### ISSUE THREAD

**Issue by fikunmi-ap** [jito-foundation/stakenet#78]
**Is your feature request related to a problem? Please describe.**
No, no problem per se

**Describe the solution you'd like**
Tracking the validators that make up the top 33% of stake
I haven't given much thought to this but it should be relatively easy to implement. Just track what validators make up 33% of total stake.

**Describe alternatives you've considered**
Computing this value off-chain but that seems to defeat the purpose of stakenet

**Additional context**
This feature is one step on the way to what I hope will be JIP-6. Do not stake to validators in Superminority

**Comment by buffalu** [comment]
there is a field that does this located [here](https://github.com/jito-foundation/stakenet/blob/10e887a4b512a31aa356fa0e7697faa994a7177e/programs/validator-history/src/instructions/update_stake_history.rs#L50)

it is permissioned to an oracle right now since the information isn't on-chain per your observation.

in an ideal world, this oracle is decentralized to an operator set of many, potentially leveraging (re)staked assets.

**Comment by fikunmi-ap** [comment]
first AVS? :)  
gib 100k JTO grant.

thanks @buffalu, we can certainly work on decentralizing the oracle if an on-chain solution is impossible (again, haven't given it much thought.) But for now though this feature will suffice. 👍

**Comment by fikunmi-ap** [comment]
fixed.
